const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const serversRoot = path.join(projectRoot, 'servers');
const dockerRoot = path.join(projectRoot, 'docker');

const runMcpBatTemplate = `@ECHO OFF
REM This file is auto-generated by 'npm run setup'. Do not edit manually.
cd /D "%~dp0"
npm run --silent start -- %*
`;

const runMcpShTemplate = `#!/bin/sh
# This file is auto-generated by 'npm run setup'. Do not edit manually.
DIR=$(cd "$(dirname "$0")" && pwd)
cd "$DIR"
npm run --silent start -- "$@"
`;

module.exports = {
  projectRoot,
  serversRoot,
  dockerRoot,
  runMcpBatTemplate,
  runMcpShTemplate,
}; 